# Generated by Django 3.2.4 on 2024-04-28 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_expense_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='categoy',
            new_name='category',
        ),
    ]
